CREATE TABLE products (
	id INT(11) NOT NULL AUTO_INCREMENT,
	product_name VARCHAR(150) NOT NULL,
	price DECIMAL(10,2) NOT NULL DEFAULT '0.00',
	description TEXT NOT NULL,
	quantity INT(11) NOT NULL,
	date_create TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id),
);

CREATE TABLE clients (
	id INT(11) NOT NULL AUTO_INCREMENT,
	email VARCHAR(250) NOT NULL,
	password VARCHAR(250) NOT NULL,
	date_create TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
);

CREATE TABLE orders (
	id INT(11) NOT NULL AUTO_INCREMENT,
	client_id INT(11) NOT NULL,
	product_id INT(11) NOT NULL,
	quantity INT(11) NOT NULL DEFAULT '1',
	description TEXT NOT NULL,
	sell_status TINYINT(1) NOT NULL DEFAULT '0',
	date_create TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id),
	CONSTRAINT FK_products FOREIGN KEY (product_id) REFERENCES products (id),
	CONSTRAINT FK_clients FOREIGN KEY (user_id) REFERENCES users (id)
);




